repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        exclude: _.*\.py$
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.10
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  #Â Commented out for the moment.
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.17.0
  #   hooks:
  #     - id: mypy
  #       args:
  #         - --config-file=pyproject.toml
  #       additional_dependencies:
  #         - numpy
  #         - matplotlib
  #         - seaborn
  #         - networkx
  #         - plotly
  #         - pandas
  #         - tqdm
  #         - requests
  #         - gql
  #         - graphql-core
  #         - galois
  #         - types-seaborn
  #         - types-networkx
  #         - pandas-stubs
  #         - types-tqdm
  #         - types-requests
  #         - plotly-stubs
  #         - scipy-stubs
  #         - semver

  - repo: https://github.com/crate-ci/typos
    rev: v1.42.0
    hooks:
      - id: typos

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
    - id: bandit
      args: [-c, pyproject.toml]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        # Optional extra validations from SchemaStore:
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.9
    hooks:
      - id: actionlint

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.8.3
    hooks:
      - id: pydoclint
