---
name: Build docs
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-deltakit-token:
    name: Check if Deltakit token exists
    runs-on: ubuntu-slim
    outputs:
      exists: ${{ steps.deltakit-token.outputs.exists }}
    steps:
        - id: deltakit-token
          env:
              DELTAKIT_TOKEN: ${{ secrets.DELTAKIT_TOKEN }}
          if: ${{ env.DELTAKIT_TOKEN != '' }}
          run: echo "exists=true" >> $GITHUB_OUTPUT

  build-docs:
    needs: [check-deltakit-token]
    if: needs.check-deltakit-token.outputs.exists == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Synchronisation of packages
        run: uv sync --python 3.13 --resolution highest --group docs

      - name: Build documentation
        run: uv run sphinx-build -W -b html docs docs/_build/html
        env:
          DELTAKIT_TOKEN: ${{ secrets.DELTAKIT_TOKEN }}
